$ANSIBLE_VAULT;1.1;AES256
39343065613138353330346266616432376234313664333539613932643138646437616430653736
3531303962383230623736373133303465383831623736320a626333656434643934636237666534
65623339326663346437356539333862346265366431376330313861623363323165623065633235
3261373737333163620a323631353730343433353038396137383439366233333738613830623262
38616163626333663564643733396462616336333761363061633637343635343565303933313038
30666239653936393231363561623066363263616232343933336562336465666465316338393961
376638383537646662643132636335353535
